dist: xenial
language: php
php:
  - 7.2
git:
  depth: 2
addons:
  apt:
    packages:
      - ant
before_script:
  - composer install -d src/Symfony
  - composer install -d src/Laravel
  - php src/Laravel/artisan key:generate
script:
  ant -f src/Symfony/build.xml && ant -f src/Laravel/build.xml
