dist: xenial
language: php
php:
  - 7.2
git:
  depth: 2
addons:
  apt:
    packages:
      - ant
install: ant deps
before_script:
  - cd src/Symfony && composer install
  - cd src/Laravel && composer install
script:
  ant -f src/Symfony/build.xml && ant -f src/Laravel/build.xml
